name: Tests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - php: 7.1.8
          - php: 7.1.28
          - php: 7.1
          - php: 7.1
            setup: lowest
          - php: 7.1

          - php: 7.2.0
          - php: 7.2.15
          - php: 7.2
          - php: 7.2
            setup: lowest
          - php: 7.2

          - php: 7.3.0
          - php: 7.3.5
          - php: 7.3
            setup: lowest
          - php: 7.3

          - php: 7.4
            setup: lowest
          - php: 7.4
            coverage: true

          - php: 8.0
            composerOptions: --ignore-platform-req=php

          - php: 8.1
            composerOptions: --ignore-platform-req=php

          - php: 7.4
            laravel: true

          - php: 7.3
            styleCheck: true

    name: ${{ matrix.styleCheck && 'Style check - ' || '' }}${{ matrix.laravel && 'Laravel compatibility - ' || '' }}${{ matrix.coverage && 'Coverage - ' || '' }}PHP ${{ matrix.php }} - ${{ matrix.setup || 'stable' }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: json
        tools: composer:v2
        coverage: ${{ matrix.coverage }}

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: |
        if [[ "${{ matrix.styleCheck }}" != 'true' ]]; then
          composer remove --no-update phpmd/phpmd friendsofphp/php-cs-fixer --no-interaction --dev;
        fi;
        if [[ "${{ matrix.laravel }}" != 'true' ]]; then
          composer remove --no-update kylekatarnls/multi-tester --no-interaction --dev;
        fi;
        composer update --prefer-dist --no-progress --no-suggest --prefer-${{ matrix.setup || 'stable' }} ${{ matrix.composerOptions }};

    - name: Run test suite
      run: |
        if [[ "${{ matrix.laravel }}" != 'true' && "${{ matrix.styleCheck }}" != 'true' && "${{ matrix.coverage }}" = 'true' ]]; then
          vendor/bin/phpunit --coverage-clover=coverage.xml --coverage-text;
          cp coverage.xml clover.xml;
        fi;
        if [[ "${{ matrix.laravel }}" != 'true' && "${{ matrix.styleCheck }}" != 'true' && "${{ matrix.coverage }}" != 'true' ]]; then
          vendor/bin/phpunit;
        fi;
        if [[ "${{ matrix.laravel }}" != 'true' && "${{ matrix.styleCheck }}" = 'true' ]]; then
          composer style-check;
        fi;
        if [[ "${{ matrix.laravel }}" = 'true' ]]; then
          vendor/bin/multi-tester;
        fi;
      env:
        PHP_VERSION: ${{ matrix.php }}
        REDIS_HOST: 127.0.0.1
        REDIS_PORT: 6379
      continue-on-error: true

    - name: Code Climate Test Reporter
      if: matrix.coverage == 'true'
      uses: aktions/codeclimate-test-reporter@v1
      with:
        codeclimate-test-reporter-id: ${{ secrets.CC_TEST_REPORTER_ID }}
        command: after-build -t clover
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    - name: Coverage
      if: matrix.coverage == 'true'
      run: |
        bash <(curl -s https://codecov.io/bash);
        composer require codacy/coverage;
        vendor/bin/codacycoverage clover coverage.xml;
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        PHP_VERSION: ${{ matrix.php }}
